//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccelaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressModel
    {
        public int ADDRESS_ID { get; set; }
        public int PERSON_ID { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTAL_CODE { get; set; }
    
        public virtual PersonModel TBL_PERSON { get; set; }
    }
}
