USE [Accela]
GO

/****** Object:  Table [dbo].[TBL_ADDRESS]    Script Date: 03/12/2020 23:27:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_ADDRESS](
	[ADDRESS_ID] [int] IDENTITY(1,1) NOT NULL,
	[PERSON_ID] [int] NOT NULL,
	[STREET] [varchar](255) NULL,
	[CITY] [varchar](255) NULL,
	[STATE] [varchar](255) NULL,
	[POSTAL_CODE] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ADDRESS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_ADDRESS]  WITH CHECK ADD FOREIGN KEY([PERSON_ID])
REFERENCES [dbo].[TBL_PERSON] ([PERSON_ID])
GO


