USE [master]
GO

/****** Object:  Database [Accela]    Script Date: 04/12/2020 00:11:17 ******/
CREATE DATABASE [Accela]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Accela', FILENAME = N'C:\Users\chris\OneDrive\Documents\AccelaApp\AccelaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AccelaDB_log', FILENAME = N'C:\Users\chris\OneDrive\Documents\AccelaApp\AccelaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Accela].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Accela] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Accela] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Accela] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Accela] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Accela] SET ARITHABORT OFF 
GO

ALTER DATABASE [Accela] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Accela] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Accela] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Accela] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Accela] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Accela] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Accela] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Accela] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Accela] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Accela] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Accela] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Accela] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Accela] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Accela] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Accela] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Accela] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Accela] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Accela] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Accela] SET  MULTI_USER 
GO

ALTER DATABASE [Accela] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Accela] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Accela] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Accela] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Accela] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Accela] SET QUERY_STORE = OFF
GO

USE [Accela]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Accela] SET  READ_WRITE 
GO


